### PR TITLE
add support for cname/aliases and wildcards

### PR DESCRIPTION
**Pull request by hjanuschka**
lets you define an array with cnames/aliases - and regex hosts with "wildcards" option

### CODE REVIEW

**Comment by ekristen** [comment]
@hjanuschka thanks for the PR. I have a few questions though ...

I'm curious to know your use cases for this, just helps me better understand. Also specifically on the wildcards, why not just support wildcards on the `hosts` configuration to make things more simple? Why its own object in the config?

**Comment by hjanuschka** [comment]
we are deploying the dns-proxy in our company - and we have about 200 dns records wich should be handled by DNS proxy - and cname/alias are very important for us :smile:  (we have a bunch of hosts wich we are rewriting to one server - this server has an ip - set in the cnames, changing the servers ip only requires one config change)

about the wildcard, first of all, i didn't want to break anything so i decided to go the "own object" way (and well its my first node contribution).

we wanted wildcards - to be able to use regex on domain names - like we have:

docker01.domain.com
docker01.domain.com
docker02.domain.com
docker-dev.domain.com


and they all should end up on the same server so the wildcard would be `docker.*\\.domain\\.com` 



regards
helmut

**Comment by ekristen** [comment]
Wow you are using this in your company? Sweet :) 

This project is young and pretty clean so I'm just being a little cautious with merging stuff in, but with that said I want to help you, especially since you are using it! :) Bare with me a little please.

The `domains` config is perfect solution for your use case with the docker01,02,dev pointing to the same entry. If you just do `docker.com: 192.168.1.127` anything you query the ends with docker.com will end up being 192.168.1.127.

Example:
```javascript
domains: {
  'docker.com': '192.168.1.127'
}
```

`hi.docker.com`, `anything.docker.com` all end up being `192.168.1.127`

I think that solves the wildcard ... but not the aliases.

Let me know.

**Comment by ekristen** [comment]
I'm also thinking for the longevity that it might make sense to do the following ...

Just use the hosts directive, but allow the right side of the host entry to be an alias, this example ...

```
hosts: {
  'devlocal': '127.0.0.1',
  'livesystem': 'live',
  'live': '127.127.0.1
}
```

Then when a lookup is done against livesystem, it'll lookup `live` and return `127.127.0.1` 

It streamlines things a bit, thoughts?

**Comment by ekristen** [comment]
I tweaked some stuff and created https://github.com/ekristen/dns-proxy/tree/aliases basically it supports aliases across the board in `domains` and `hosts` which I think meets your objectives still? 

Examples Config
```json
{
  "port": "5151",
  "hosts": {
    "dev": "172.16.11.11",
    "test": "dev"
  },
  "domains": {
    "docker": "192.168.1.127",
    "testing": "test",
    "test": "192.192.168.168"
  },
}
```

Example Queries:
1. `dig -p 5151 hi.testing` => `192.192.168.168`
2. `dig -p 5151 anything.testing` => `192.192.168.168`
3. `dig -p 5151 first.docker => `192.192.168.168`
4. `dig -p 5151 second.docker => `192.192.168.168`
5. `dig -p 5151 test` => `172.16.11.11`
6. `dig -p 5151 dev` => `172.16.11.11`

**Comment by ekristen** [comment]
If you want to test this, you should be able to checkout the branch `aliases` and do an npm install -g or just run it locally.

**Comment by hjanuschka** [comment]
tested this :smile: very nice think this solves my alias issues :) 
in addition it maybe nice to specify a real cname (like in bind) - wich gets resolved.

like specify:
    hosts: {
          "my.domain.com": "sometoplevel.com"
    }

if sometoplevel.com - is not found in the domains object - resolv it using the supplied "nameservers"



about the wildcard thing:
i do not only need simple wildcards like you described, i want to be able to use full regex to match in the hosts object.


so that a few more complex scenarios are possible:

    hosts: {
          "app-.*-stage.domain.com": "alias1"
          "app-.*-dev.(domain1|domain2).com": "alias2"
    }


with js `.match()` there should be an easy regex comaptible way.

**Comment by ekristen** [comment]
@hjanuschka I'm going to close this pull request for now, and I'll merge my aliases branch in and tag and release a new version. 

RE: cname comment ... the domains directive in dns-proxy is really so that you can override the answer for an entire domain, but realistically it doesn't have to be a domain, the way the matching is done, if the entry in domain is `ogle.com` and you do `dig google.com` you'll get whatever response is configured against `ogle.com`, does that make sense?

I'll open a ticket about adding regex support. I am concerned about speed of responses if there are several regexs that have to be matched ... but either way I think adding support shouldn't be a problem, worst case scenario I make it a configuration option, that way if people don't want to use regex they can just leave it off to keep things lightweight. https://github.com/ekristen/dns-proxy/issues/7

**Pull request closed without merging**
