### PR TITLE
Added syntax highlighting for json in readme

### PR DESCRIPTION
**Pull request by frozzare**

### CODE REVIEW

**Comment by ekristen** [comment]
Thanks, I just realized though it should be json as that is what the rc module expects, and I should probably state they are excerpts. I'll merge for now because you are right those are js snippets, but I'll fix for json.

**Comment by ekristen** [comment]
@frozzare I updated the docs a bit, hopefully it makes a little more sense.

**Comment by frozzare** [comment]
Ah, yes that make more sense to use `json` instead of `js` :)

**Comment by ekristen** [comment]
I welcome any and all feedback on the project to. Please let me know how it goes.

**Pull request merged**
